### PR TITLE
Changes to make diff.d usable with current dmd

### PR DESCRIPTION
**Pull request by francais01**
I found that these changes allowed me to use this library with my dmd version 2.067.0

### CODE REVIEW

**Comment by francais01** [comment]
I haven't looked at similar issues in match.d and patch.d however...

**Comment by s-ludwig** [comment]
I think that instead of `int` or `long`, `sizediff_t` would be the right choice to use. Then, at some point, `sizediff_t` should be changed to `size_t` where possible.

Otherwise looks good to merge.

**Comment by s-ludwig** [comment]
Having said that, I'll just merge now and and then go over the whole code once to see if there is anything else that can be cleaned up/fixed. Thanks for your help!

**Comment by francais01** [comment]
Glad to be of some help. I see you've changed a few things already, including finding the missing "ref" which I found today also. I'll probably try out your code tomorrow. Thanks!

**Comment by s-ludwig** [comment]
Yeah, my hope was to get all tests to pass yesterday, but I got stuck in the patch tests where I couldn't find the mistake. Would be great to get this to completion.

If I get some more time, I'll probably start to refactor the code by putting the main freestanding functions into structs. These could then be used to configure the different thresholds and other parameters instead of resorting to global variables. Also many of the functions can probably be made private.

**Pull request merged**
